views/log.ejs
=> Test branch and merge

assets/scripts/lobby/chat4.js, assets/scripts/lobby/options.js, assets/scripts/lobby9.js, views/lobby.ejs
Files changed: 
assets/scripts/lobby/options.js
views/lobby.ejs
Added the new button under the MISC tab, to set all the highlight colors to yellow, like on TRP
=> Added button to set all the highlight colors to yellow (like on the TRP) + Added possibility to unhighlight all the players

assets/scripts/lobby/chat4.js, sockets/sockets.js
closes #57
only remaining thing to be decided is if Player X muted Z, but Y quotes Z, do we show Z's sentence or not? on one hand it was originally said by Z, on the other, it was Y's choice to resend it.
=> Verify quotes

models/user.js, routes/index.js, routes/profile.js, views/profile/edit.ejs, views/profile/profile.ejs
Fixed issue  [#35] Added possibility to hide stats.
Commented out console.log function that are exposing data even if visually we can't see that div.
Also we are not returning XHR stats data if the user has set the boolean to false.
Added new property on user object.
=> Added possibility to hide stats.

assets/scripts/lobby/sockets/sockets4.js
* Test 1
* Test 2
* Fixed the typo
Please accept this pull request!
=> Aquaint typo fix

assets/scripts/lobby/icons.js, assets/scripts/lobby9.js, gameplay/avalon/cards/ref of the lake.js, gameplay/avalon/phases/assassination.js, gameplay/avalon/phases/lady.js, gameplay/game.js, models/gameRecord.js, sockets/sockets.js, views/log.ejs
A new card that is the same as Lady of the Lake but can only be used after the last mission failed.
=> Ref of the lake

gameplay/avalon/phases/assassination.js, views/log.ejs
Renamed some text for assassination phase.
=> Assassination rename text

views/index.ejs
changed "out wit" to "outwit" lol
=> changed out wit to outwit

views/lobby.ejs, views/log.ejs
Reverts vck3000/ProAvalon#145
Doesn't look good on PC
=> Revert "Changed middle box and status message box layout. Better for phones"

models/statsCumulative.js, routes/index.js
Simplified code a lot. I will now manually update stats locally on my personal computer until I implement code to automatically recalculate the stats after each game ends. Loading the whole 50megabytes of raw data into the server to process shall be avoided. Instead, it should be cumulatively added.
=> Stats fix2

routes/index.js, views/community.ejs
You can reach the page by "/community", I did not add a link in navbar
=> Created a Community Page

models/avatarRequest.js, routes/profile.js, views/mod/customavatar.ejs, views/profile/changeavatar.ejs
=> Added custom avatar message to mods in request

routes/index.js, views/statistics.ejs
somewhat hacky approach, feel free to modify or circle back with suggestions :)
=> Adding button to download anonymized stats from proavalon

views/mod/customavatar.ejs, views/profile/changeavatar.ejs
- Must have at least 20% of the original colour (blue or red) and a minimum of the opposite allegiance's colour (approximation).
- Must keep the wordage to a minimum.
- Moderators have final say based on their judgment. Free feel to consult them before making it to ensure it will adhere to these guidelines.
=> Added a few more custom avatar rules:

sockets/sockets.js
server notifies whenever a user joins where his ip is already used by another player
also runs /mcompareips for mods when they log in
=> Mcompareips auto notify

sockets/sockets.js
Fixed bug that sent the mod warnings to all players, not just mods whenever someone's ip matched.
=> auto mcompareips hotfix

gameplay/game.js, sockets/sockets.js
which will be shown publicly in the end.
=> Implements #173: lets players/specs submit a guess of who Merlin is,

gameplay/game.js, gameplay/playersReadyNotReady.js, gameplay/room.js, sockets/bot.js, sockets/sockets.js
Bot API integration code. A testing server is available here:
https://testing-proavalon.herokuapp.com/
Bot API spec is available here:
http://jack.plus/proavalon-bot-api/
=> Add bot API integration

views/partials/header.ejs
Updated header: Lobby/rules/stats as standalone navbar buttons, Community (forums/facebook) and Development (log/about/github) under dropdown menus.
=> added community and dev navbar dropdowns

gameplay/game.js
spectator to be not ready (and game not to start)
=> Fix bug where spectator leaving during ready-not ready phase causes

README.md
I added some links to the README, made the indentation consistent, and put the same amount of spacing in front of each header. This is one of my first contributions on GitHub so please let me know if I'm doing anything wrong!
I'd also like to add better instructions on how to install MongoDB as well as specify example folder paths for Mac as well.
Sorry for nitpicking, and I'll also take a look at some other issues to work on!
=> made spacing consistent and added links to third parties

views/index.ejs
=> fixes sabatoging to sabotaging in index.ejs

gameplay/avalon/cards/lady of the lake.js, gameplay/avalon/cards/ref of the rain.js, gameplay/avalon/cards/sire of the sea.js, gameplay/avalon/phases/assassination.js, gameplay/avalon/phases/lady.js, gameplay/avalon/phases/ref.js, gameplay/avalon/phases/sire.js, gameplay/avalon/roles/assassin.js, gameplay/avalon/roles/isolde.js, gameplay/avalon/roles/merlin.js, gameplay/avalon/roles/mordred.js, gameplay/avalon/roles/morgana.js, gameplay/avalon/roles/oberon.js, gameplay/avalon/roles/percival.js, gameplay/avalon/roles/resistance.js, gameplay/avalon/roles/spy.js, gameplay/avalon/roles/tristan.js, sockets/bot.js
I think [javascript `class` syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) is a lot more readable than assigning methods onto the prototype. This won't change the functionality of the game, just the way that the code is written, and will make the project easier to maintain.
=> Migrate to class syntax

app.js, models/patreonId.js, models/patreonInfoTemp.js, models/user.js, myFunctions/patreonHelper.js, package.json, routes/patreon.js, routes/profile.js, views/profile/edit.ejs
The following will be implemented in the rewards PR:
- Add in user rewards
- Detect the level of pledge the user has
=> Patreon implementation

models/user.js, routes/index.js, routes/indexNoCaptcha.js
Just to clean up the code a little bit. This will work with existing documents, i.e. queries will return the default value as part of the object if no existing value is found.
=> moved default user values into mongoose schema

gameplay/game.js, views/log.ejs
Small adjustment to allow for inclusion of mtogglepause command. Paused is a new phase in commonPhases and togglePause is the game.js pausing function.
=> Moderator Command for Pausing Games

assets/stylesheets/lobby.css, gameplay/game.js, gameplay/gameWrapper.js, gameplay/room.js, routes/index.js, routes/middleware.js, sockets/bot.js, sockets/sockets.js, views/index.ejs, views/log.ejs
A couple adjustments to game finishing callbacks and creation of update callbacks. Should the way update callbacks are done be different?
Also small bug fix on spectator list inside games, it wasn't using display usernames.
=> Callback Changes

sockets/sockets.js, views/mod/mod.ejs, views/rules.ejs
After getting the rules from the forums, I added to rules page on the website while keeping the layout as close to the forums as possible. Is this what you are looking for?
=> Add rules from forums to rules page on website

gameplay/commonPhases/pickingTeam.js, gameplay/room.js, sockets/sockets.js
Added a timeout to the destruction function of room to allow for some wiggle room if the site lags and kicks everyone off. If they manage to be disconnected for more than 30 seconds the room will still be lost. Also removed the error message stating that not the right team size has been picked as it's dealt with anyway.
=> Small Bugfixes

.circleci/config.yml
- Will only push to DockerHub if the branch is newPA.
- Other branches will have their code built and tested.
=> Finalised Circle CI auto push to DockerHub

README.md
Since we're revamping a lot of the technologies, we should keep the README up-to-date as well.
We can leave this PR open to merge changes to the README as the project goes on.
=> removed outdated documentation, added some links and fixed installation instructions

packages/frontend/components/colours.tsx, packages/frontend/components/nav.tsx, packages/frontend/pages/index.tsx
- Added a colours.tsx file.
- Mobile view is not complete yet
=> Added desktop navbar.

docker-compose.yml, packages/backend/package-lock.json, packages/backend/package.json, packages/backend/src/app.controller.spec.ts, packages/backend/src/app.module.ts, packages/backend/src/auth/auth.controller.spec.ts, packages/backend/src/auth/auth.controller.ts, packages/backend/src/auth/auth.module.ts, packages/backend/src/auth/auth.service.spec.ts, packages/backend/src/auth/auth.service.ts, packages/backend/src/auth/jwt-constants.ts, packages/backend/src/auth/jwt.strategy.ts, packages/backend/src/auth/local.strategy.ts, packages/backend/src/chat/chat.service.spec.ts, packages/backend/src/getEnvVars.js, packages/backend/src/test/app.e2e.spec.ts, packages/backend/src/test/auth.e2e.spec.ts, packages/backend/src/users/dto/create-user.dto.ts, packages/backend/src/users/user.model.ts, packages/backend/src/users/users.module.ts, packages/backend/src/users/users.service.spec.ts, packages/backend/src/users/users.service.ts
Updated all tests except for auth.e2e login after sign up test
=> Added Mongo with Typegoose

packages/backend/src/test/auth.e2e.spec.ts, packages/backend/src/users/dto/create-user.dto.ts
=> Tweak username input validation

views/profile/profile.ejs
Feels like this is something that should be gender neutral that is all :)
=> Change wording on hiding stats

Dockerfile.dev, docker-compose.yml
I had some issues during my setup of this project. This hopefully fixes them for everyone.
=> Fix setup errors

packages/frontend/components/lobby/rightPanel/gameCard.tsx, packages/frontend/pages/game/[id].tsx
- it's not even a skeleton, it just has a link back to /
- it uses the nextjs router hook to get the id of the game from the link
- add Links to GameCards to route to game pages
=> add skeleton game page

packages/frontend/components/layout/Layout.tsx, packages/frontend/components/lobby/lobbyDesktop.tsx, packages/frontend/components/lobby/lobbyMobile.tsx, packages/frontend/components/lobby/rightPanel/gamesMenu.tsx, packages/frontend/pages/game/[id].tsx
- implement Layout component for reusing logo and nav across other
components
- simplify lobbyDesktop and fix the overlap between the content and
navbar
=> fix lobby nav overlap, implement Layout

packages/frontend/components/layout/Layout.tsx, packages/frontend/components/lobby/lobbyDesktop.tsx, packages/frontend/components/lobby/lobbyMobile.tsx, packages/frontend/components/lobby/mainPanel/message.tsx, packages/frontend/components/lobby/rightPanel/gameCard.tsx, packages/frontend/components/lobby/rightPanel/gamesMenu.tsx, packages/frontend/pages/game/[id].tsx
=> New PA staging

packages/frontend/components/game/game.tsx, packages/frontend/components/game/tabPane.tsx, packages/frontend/package-lock.json, packages/frontend/package.json, packages/frontend/pages/_app.tsx, packages/frontend/pages/game/[id].tsx
- styled-jsx added as explicit dependency to use it's resolver
- @types/styled-jsx added for same purpose
- added new light-inactive color, needs a night variant
=> add TabPane component, update Game with layout

packages/frontend/components/lobby/lobbyIndex.tsx, packages/frontend/store/auth/sagas.ts
- socket can now be used on other pages
=> move socket open/close to saga

assets/scripts/lobby/buttonEventListeners2.js, assets/scripts/lobby/sockets/sockets4.js, gameplay/game.js, gameplay/gameWrapper.js, gameplay/room.js, models/user.js, routes/middleware.js, sockets/sockets.js, views/lobby.ejs, views/profile/profile.ejs
Implementation of the rating system to run the rating system beta.
=> Rating System Beta

packages/frontend/components/chat/chat.tsx, packages/frontend/components/chat/message.tsx, packages/frontend/components/game/tabPane.tsx, packages/frontend/components/index/index.tsx, packages/frontend/components/index/loginSignUpForm.tsx, packages/frontend/components/lobby/leftPanel/announcements.tsx, packages/frontend/components/lobby/lobbyMobile.tsx, packages/frontend/components/lobby/rightPanel/gameCard.tsx, packages/frontend/components/lobby/rightPanel/missionHistory.tsx, packages/frontend/components/nav/navDesktop.tsx, packages/frontend/components/nav/navMobile.tsx, packages/frontend/components/nav/navRight.tsx, packages/frontend/pages/_app.tsx
- import all Monteserrat weights into family, so font-weight can be used
to change between them
- replace semantic-ui tab with custom tab pane
=> fix font family, replace semantic tab

packages/frontend/.eslintrc.json, packages/frontend/components/chat/chat.tsx, packages/frontend/components/game/game.tsx, packages/frontend/components/game/useGame.ts, packages/frontend/components/lobby/lobbyIndex.tsx, packages/frontend/components/resize.tsx, packages/frontend/effects/useAuth.ts, packages/frontend/package-lock.json, packages/frontend/package.json, packages/frontend/pages/_app.tsx
- TS to 3.9
- Next to 9.4
- required adding undefined to possible types of router.query.id
- eslint-plugin-react-hooks
- added to eslint config, and fixed errors it found
- refactored Resize effect into component (so it has Redux access)
- typing updates
=> update npm packages

README.md, packages/frontend/components/chat/chat.tsx, packages/frontend/components/chat/message.tsx, packages/frontend/components/game/tabPane.tsx, packages/frontend/components/index/loginSignUpForm.tsx, packages/frontend/components/lobby/lobbyMobile.tsx, packages/frontend/components/nav/navMobile.tsx, packages/frontend/components/nav/navRight.tsx, packages/frontend/components/nav/navRightMobile.tsx, packages/frontend/package-lock.json, packages/frontend/package.json, packages/frontend/pages/_document.tsx
- tweak styles (removing semantic-ui made some things look funny)
=> Remove semantic-ui, add user actions to mobile nav

packages/backend/docker-compose-redis-testing.yml, packages/backend/src/auth/online-players/online-players.service.ts, packages/backend/src/auth/online-sockets/online-sockets.service.ts, packages/backend/src/games/games.gateway.ts, packages/backend/src/games/games.service.ts, packages/backend/src/redis-client/redis-client.service.ts, packages/backend/src/test-integration/games.service.ispec.ts, packages/backend/src/test/sockets.e2e.spec.ts, packages/backend/src/util/redisSocketIoAdapter.ts
- Added framework to use Redis concurrently across multiple app
instances.
- Added E2E tests for concurrency, chat, game creation and game joining.
=> Added Redis synchronisation and game service.

packages/backend/proto/lobbyProto.ts, packages/backend/src/commands/user-commands/commands/create-room.service.ts, packages/backend/src/games/game.ts, packages/backend/src/games/games.gateway.ts, packages/backend/src/games/games.service.ts, packages/backend/src/games/types.ts, packages/backend/src/test-integration/games.service.ispec.ts, packages/frontend/proto/lobbyProto.ts, proto/lobbyProto.ts
- Saves to Redis
- Validates user given inputs
=> Added game state on creation

packages/frontend/components/game/tabPane.tsx, packages/frontend/components/game/voteHistory.tsx, packages/frontend/components/icon.tsx, packages/frontend/pages/_app.tsx, packages/frontend/store/game/actions.ts, packages/frontend/store/game/reducer.ts, packages/frontend/store/game/types.ts, packages/frontend/store/index.ts
~This isn't ready yet, but I wanted to get initial feedback on the shape of the game state and how the vote history looks~
Should be ready now!
=> Add game state reducer and vote history component

gameplay/game.js
=> Fix Indexing Error

packages/frontend/components/game/game.tsx, packages/frontend/components/game/gameContent.tsx, packages/frontend/components/game/tabPane.tsx
- remove extra divs by passing classes straight to children
=> Add gameContent component, refactor game component

package.json, packages/backend/src/test-integration/games.service.ispec.ts, packages/frontend/components/layout/layout.tsx
- fix left end of banner not aligning with chat
- removed extra div around logo
- replaced connect with useSelector
- replaced wrapper div with more semantic header
=> Refactor layout component, fix banner alignment

views/profile/profile.ejs
Small change so that your rating on your profile is consistent with the displays in #357
=> Fix profile rating

assets/scripts/lobby/sockets/sockets.js, assets/stylesheets/lobby.css, src/views/lobby.ejs, src/views/log.ejs, src/views/profile/profile.ejs
- Don't search if there's no name typed in
- Don't show the border if there's no content in a user profile
- Added games counter in lobby display
=> Improvements to lobby and profile page display

src/sockets/sockets.ts
Closes https://github.com/vck3000/ProAvalon/issues/433
=> Switched command getmutedplayers to muted.

assets/scripts/lobby/options.js, src/views/partials/header.ejs
Closes https://github.com/vck3000/ProAvalon/issues/437
=> Removed Licking from options

assets/scripts/lobby.js, assets/scripts/lobby/chat.js, assets/scripts/lobby/sockets/commands.js, assets/stylesheets/lobby.css, package.json, src/rewards/getPatreonDetails.ts, src/routes/mod.js, src/sockets/quote.ts, src/sockets/sockets.ts, src/sockets/tests/quote.test.ts, src/views/log.ejs, yarn.lock
closes https://github.com/vck3000/ProAvalon/issues/438
=> [WIP] Removed multer.

assets/scripts/lobby.js, assets/stylesheets/lobby.css, src/views/components/report/hydrate.tsx, src/views/lobby.ejs
Closes https://github.com/vck3000/ProAvalon/issues/442
=> Fixed report button cloning.

.eslintrc.json, src/myFunctions/IPLinkedAccounts.js, src/myFunctions/createNotification.js, src/myFunctions/patreonHelper.js, src/sockets/sockets.ts
Also fixes some issues with the last cleanup.
=> Cleanups v2

src/gameplay/room.js, src/sockets/sockets.ts, src/views/log.ejs
This is the first of many fixes, please do not merge
=> Fix the issues allowing the current site situation

src/sockets/sockets.ts, src/views/log.ejs
Fixes this particular injection:
=> Fixed injection into server text.

package.json, src/gameplay/game.ts, src/sockets/commands/mod/index.ts, src/sockets/commands/mod/m.ts, src/sockets/commands/mod/mannounce.ts, src/sockets/commands/mod/mclose.ts, src/sockets/commands/mod/mforcemove.ts, src/sockets/commands/mod/miplinkedaccs.ts, src/sockets/commands/mod/mkill.ts, src/sockets/commands/mod/mrevealallroles.ts, src/sockets/commands/mod/mtogglepause.ts, src/sockets/sockets.ts, src/sockets/tests/modCommands.test.ts, src/sockets/types.ts, yarn.lock
Finally finished moving out all the mod commands!
=> Cleanups v8

src/modsadmins/tournamentOrganizers.ts
Due to tournament finishing, removed the existing list of tourney organisers
=> Removed tourney organisers

src/views/index.ejs
=> Added disord link to main page

src/gameplay/game.ts, src/views/log.ejs
Fixed bug where mute spectators could be toggled during game
=> Mute spectators

src/sockets/matchmakingQueue.ts, src/sockets/sockets.ts
=> Push users who apped but match found rejected to front of queue

src/gameplay/anonymizer.ts, src/gameplay/game.ts, src/gameplay/gameTimer.ts, src/views/changelog.ejs
Addressing issue https://github.com/vck3000/ProAvalon/issues/610, #608, #609
=> Anon mode fixes

src/views/about.ejs
Fixed avatar link and updated discord username
=> Fixed avatar link and updated discord user

package.json, src/gameplay/game.ts, src/gameplay/gameTimer.ts, src/sockets/matchmakingQueue.ts, src/sockets/sockets.ts, src/sockets/tests/matchmakingQueue.test.ts, src/views/about.ejs, src/views/changelog.ejs, webpack.dev.js, yarn.lock
Updated matchmaking to allow for 6-8p matches
Waits 10seconds before finding a match from when a user last joins
Prioritises larger lobbies
Addresses issue #613
=> Dynamic Matchmaking

src/sockets/sockets.ts
=> Updated help msg for users with less than 3 games for ranked queue

src/gameplay/game.ts, src/gameplay/voidGameTracker.ts
=> Updated vote messages

assets/scripts/lobby/chat.js, assets/scripts/lobby/options.js, src/views/changelog.ejs, src/views/partials/header.ejs
=> Added display option for chat in hours:min:sec

assets/scripts/lobby/buttonEventListeners2.js, src/sockets/sockets.ts
Timeouts can only be max of 60min. They also have to be valid integers between 0 - 60
=> Added constraints for timeouts

assets/scripts/lobby.js, src/gameplay/game.ts, src/sockets/sockets.ts
- Leaving a room after a game finished no longer attempts to vote to pause a timeout
- Client display for timer now displays correctly for certain timezones
=> Bugfixes for Timers

src/util/vpnDetection.ts
Documentation here: https://getipintel.net/free-proxy-vpn-tor-detection-api/.
Implements a simple check to be used in conjunction with another VPN detection service
=> Added secondary vpn check

src/sockets/commands/user/voidgame.ts
=> Updated /voidgame helper message

src/util/vpnDetection.ts
Minor variable renames + reformatted logic
Updated console log formats
=> VPN Detection updates

src/views/mod/customavatar.ejs, src/views/partials/header.ejs
=> Bugfix for vote history display. Resized mod process avatar view

src/sockets/sockets.ts
=> Updated expired avatar notification message for visibility

assets/scripts/lobby/buttonEventListeners2.js, assets/scripts/lobby/sockets/sockets.js, src/views/lobby.ejs
Added default value to gameModeSelect on startup
=> Bugfix where game mode was occassionally null

src/views/changelog.ejs, src/views/components/readyPrompt/readyPrompt.tsx
Unfocus the 'Accept' button on Ready Prompts when opened
=> Bugfix - Autoaccept match

assets/stylesheets/profile.css
=> Fixed mobile view of avatars in edit page

src/databaseAdapters/user.ts, src/routes/profile/avatarRoutes.tsx, src/views/changelog.ejs, src/views/components/avatar/avatarHome/avatarHome.tsx
=> Add: User reset avatar to default

src/databaseAdapters/user.ts, src/routes/profile/avatarRoutes.tsx, src/routes/profile/index.tsx, src/views/changelog.ejs, src/views/mod/customavatar.ejs
Added mod use cases for when to approve avatars beyond an avatar library size
=> Update avatar upload limits

src/clients/victoriaMetrics/promAgent.ts
Temporarily adding a handler for failed fetch in importing metrics to vm. Investigating currently
=> Adding temp fix

docker-compose.yml, src/app.ts, src/clients/victoriaMetrics/promMetricCounter.ts, src/databaseAdapters/user.ts, src/gameplay/game.ts, src/gameplay/types.ts, src/metrics/gameMetrics.ts, src/metrics/miscellaneousMetrics.ts, src/models/user.ts, src/myFunctions/sendResetPassword.ts, src/routes/index.js, src/routes/profile/index.tsx, src/sockets/sockets.ts
=> Adding miscellaneous metrics

src/modsadmins/tournamentOrganizers.ts, src/sockets/sockets.ts
=> Added tourney announcement + update tourney mods

src/modsadmins/tournamentOrganizers.ts, src/sockets/sockets.ts
=> Post-Tourney cleanup

assets/scripts/lobby/chat.js
Muted user messages no longer display in room chat
Muted users can no longer interact with players that muted them
=> Bugfix: Muted users

assets/scripts/lobby/sockets/sockets.js, src/gameplay/room.ts
Fixes the chat history being erased and the "/roomchat is not a valid command" error message.
=> Fix chat history in private rooms
